# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.

title: Hobe Translator
# email: # 暂时注释掉邮箱
description: >- # this means to ignore newlines until "baseurl:"
  Hobe Translator 是一款强大的翻译软件，支持多种语言之间的互译，
  特别优化了阿拉伯语的翻译体验。它提供了简洁的界面和快速的翻译响应，
  是您日常翻译工作的得力助手。
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.hobe.chat" # the base hostname & protocol for your site
github_username: hobe-translator

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .DS_Store
  - .git/
  - .github/
  - README.md

# 添加自定义设置
lang: zh # 设置网站默认语言为中文
timezone: Asia/Shanghai # 设置时区
